name: dinojump-server-ci
'on':
  workflow_dispatch: {}
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run format:check
      - run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: build-dinojump-server
          path: |
            package.json
            package-lock.json
            dist/
  deploy-heroku:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
